-- Song data for Hytte Hits game
-- This file contains all embeddable working songs (315 total)
-- Last cleaned: $(date +%Y-%m-%d)

INSERT INTO songs (title, artist, year, video_id, status) VALUES
('Rock Around the Clock', 'Bill Haley & His Comets', 1954, 'ZgdufzXvjqw', 'working'),
('Jailhouse Rock', 'Elvis Presley', 1957, 'gj0Rz-uP4Mk', 'working'),
('Great Balls of Fire', 'Jerry Lee Lewis', 1957, '7IjgZGhHrYY', 'working'),
('La Bamba', 'Ritchie Valens', 1958, 'Jp6j5HJ-Cok', 'working'),
('The Twist', 'Chubby Checker', 1960, 'im9XuJJXylw', 'working'),
('Stand by Me', 'Ben E. King', 1961, 'hwZNL7QVJjE', 'working'),
('Can''t Help Falling in Love', 'Elvis Presley', 1961, 'vGJTaP6anOU', 'working'),
('I Want to Hold Your Hand', 'The Beatles', 1963, 'jenWdylTtzs', 'working'),
('Fly Me to the Moon', 'Frank Sinatra', 1964, 'ZEcqHA7dbwM', 'working'),
('I Got You (I Feel Good)', 'James Brown', 1965, 'U5TqIdff_DQ', 'working'),
('Good Vibrations', 'The Beach Boys', 1966, 'Eab_beh07HU', 'working'),
('Respect', 'Aretha Franklin', 1967, '6FOUqQt3Kg0', 'working'),
('What a Wonderful World', 'Louis Armstrong', 1967, 'VqhCQZaH4Vs', 'working'),
('I Heard It Through the Grapevine', 'Marvin Gaye', 1968, 'hajBdDM2qdg', 'working'),
('Hey Jude', 'The Beatles', 1968, 'A_MjCqQoLLA', 'working'),
('Here Comes the Sun', 'The Beatles', 1969, 'KQetemT1sWc', 'working'),
('Let It Be', 'The Beatles', 1970, 'QDYfEBY9NM4', 'working'),
('American Pie', 'Don McLean', 1971, 'uAsV5-Hv-7U', 'working'),
('Imagine', 'John Lennon', 1971, 'YkgkThdzX-8', 'working'),
('Stairway to Heaven', 'Led Zeppelin', 1971, 'QkF3oxziUI4', 'working'),
('Superstition', 'Stevie Wonder', 1972, '0CFuCYNx-1g', 'working'),
('December, 1963', 'Frankie Valli & The Four Seasons', 1975, 'liyiT_DGREA', 'working'),
('Wish You Were Here', 'Pink Floyd', 1975, 'IXdNnw99-Ic', 'working'),
('Bohemian Rhapsody', 'Queen', 1975, 'fJ9rUzIMcZQ', 'working'),
('Dancing Queen', 'ABBA', 1976, 'xFrGuyw1V8s', 'working'),
('Stayin'' Alive', 'Bee Gees', 1977, 'fNFzfwLM72c', 'working'),
('Go Your Own Way', 'Fleetwood Mac', 1977, '6ul-cZyuYq4', 'working'),
('We Will Rock You', 'Queen', 1977, '-tJYN-eG1zk', 'working'),
('Le Freak', 'Chic', 1978, 'h1qQ1SKNlgY', 'working'),
('September', 'Earth, Wind & Fire', 1978, 'Gs069dndIYk', 'working'),
('You''re the One That I Want', 'John Travolta & Olivia Newton-John', 1978, '7oKPYe53h78', 'working'),
('YMCA', 'Village People', 1978, 'CS9OO0S5w2k', 'working'),
('Heart of Glass', 'Blondie', 1979, 'WGU_4-5RaxU', 'working'),
('I Will Survive', 'Gloria Gaynor', 1979, 'gYkACVDFmeg', 'working'),
('Don''t Stop Me Now', 'Queen', 1979, 'HgzGwKwLmgM', 'working'),
('Call Me', 'Blondie', 1980, 'StKVS0eI85I', 'working'),
('Celebration', 'Kool & The Gang', 1980, '3GwjfUFyY6M', 'working'),
('Another One Bites the Dust', 'Queen', 1980, 'rY0WxgSXdEE', 'working'),
('Don''t Stop Believin''', 'Journey', 1981, '1k8craCGpgs', 'working'),
('Physical', 'Olivia Newton-John', 1981, 'vWz9VN40nCA', 'working'),
('Don''t You Want Me', 'The Human League', 1981, 'uPudE8nDog0', 'working'),
('Hungry Like the Wolf', 'Duran Duran', 1982, 'oJL-lCzEXgI', 'working'),
('Thriller', 'Michael Jackson', 1982, 'sOnqjkJTMaA', 'working'),
('Billie Jean', 'Michael Jackson', 1982, 'Zi_XLOBDo_Y', 'working'),
('Beat It', 'Michael Jackson', 1982, 'oRdxUFDoQe0', 'working'),
('Eye of the Tiger', 'Survivor', 1982, 'btPJPFnesV4', 'working'),
('Africa', 'Toto', 1982, 'FTQbiNvZqaY', 'working'),
('Total Eclipse of the Heart', 'Bonnie Tyler', 1983, 'lcOxhH8N3Bo', 'working'),
('Karma Chameleon', 'Culture Club', 1983, 'JmcA9LIIXWw', 'working'),
('Girls Just Want to Have Fun', 'Cyndi Lauper', 1983, 'PIb6AZdTr-A', 'working'),
('Sweet Dreams', 'Eurythmics', 1983, 'qeMFqkcPYcg', 'working'),
('Every Breath You Take', 'The Police', 1983, 'OMOGaugKpzs', 'working'),
('Footloose', 'Kenny Loggins', 1984, 'wFWDGTVYqE8', 'working'),
('Like a Virgin', 'Madonna', 1984, 's__rX_WL100', 'working'),
('Purple Rain', 'Prince', 1984, 'TvnYmWpD_T8', 'working'),
('When Doves Cry', 'Prince', 1984, 'UG3VcCAlUgE', 'working'),
('What''s Love Got to Do with It', 'Tina Turner', 1984, 'oGpFcHTxjZs', 'working'),
('Careless Whisper', 'Wham!', 1984, 'izGwDsrQ1eQ', 'working'),
('Don''t You (Forget About Me)', 'Simple Minds', 1985, 'CdqoNKCCt7A', 'working'),
('We Built This City', 'Starship', 1985, 'K1b8AhIsSYQ', 'working'),
('Take On Me', 'a-ha', 1985, 'djV11Xbc914', 'working'),
('You Give Love a Bad Name', 'Bon Jovi', 1986, 'KrZHPOeOxQQ', 'working'),
('Livin'' on a Prayer', 'Bon Jovi', 1986, 'lDK9QqIzhwk', 'working'),
('The Final Countdown', 'Europe', 1986, '9jK-NcRmVcw', 'working'),
('Walk Like an Egyptian', 'The Bangles', 1986, 'Cv6tuzHUuuk', 'working'),
('Sweet Child O'' Mine', 'Guns N'' Roses', 1987, '1w7OgIMMRc4', 'working'),
('Never Gonna Give You Up', 'Rick Astley', 1987, 'dQw4w9WgXcQ', 'working'),
('I Wanna Dance with Somebody', 'Whitney Houston', 1987, 'eH3giaIzONA', 'working'),
('Don''t Worry, Be Happy', 'Bobby McFerrin', 1988, 'd-diB65scQU', 'working'),
('Paradise City', 'Guns N'' Roses', 1988, 'Rbm6GXllBiw', 'working'),
('Man in the Mirror', 'Michael Jackson', 1988, 'PivWY9wn5ps', 'working'),
('She Drives Me Crazy', 'Fine Young Cannibals', 1989, 'UtvmTu4zAMg', 'working'),
('Like a Prayer', 'Madonna', 1989, '79fzeNUqQbQ', 'working'),
('Straight Up', 'Paula Abdul', 1989, 'El1kgCqD7Xk', 'working'),
('Pump Up the Jam', 'Technotronic', 1989, '9EcjWd-O4jI', 'working'),
('Love Shack', 'The B-52''s', 1989, '9SOryJvTAGs', 'working'),
('Eternal Flame', 'The Bangles', 1989, 'PSoOFn3wQV4', 'working'),
('U Can''t Touch This', 'MC Hammer', 1990, 'otCpCn0l4Wo', 'working'),
('Vogue', 'Madonna', 1990, 'GuJQSAiODqI', 'working'),
('Wind of Change', 'Scorpions', 1990, 'n4RjJKxsamQ', 'working'),
('Nothing Compares 2 U', 'Sinéad O''Connor', 1990, '0-EF60neguk', 'working'),
('Ice Ice Baby', 'Vanilla Ice', 1990, 'rog8ou-ZepE', 'working'),
('Enter Sandman', 'Metallica', 1991, 'CD-E-LDc384', 'working'),
('Smells Like Teen Spirit', 'Nirvana', 1991, 'hTWKbfoikeg', 'working'),
('Losing My Religion', 'R.E.M.', 1991, 'xwtdhWltSIg', 'working'),
('Tears in Heaven', 'Eric Clapton', 1992, 'JxPj3GAYYZ0', 'working'),
('Creep', 'Radiohead', 1992, 'XFkzRNyygfk', 'working'),
('Under the Bridge', 'Red Hot Chili Peppers', 1992, 'GLvohMXgcBo', 'working'),
('I Will Always Love You', 'Whitney Houston', 1992, '3JWTaaS7LdU', 'working'),
('What''s Up?', '4 Non Blondes', 1993, '6NXnxTNIWkc', 'working'),
('The Sign', 'Ace of Base', 1993, 'iqu132vTl5Y', 'working'),
('What Is Love', 'Haddaway', 1993, 'HEXWRTEbj1I', 'working'),
('Dreams', 'The Cranberries', 1993, 'Yam5uK6e-bQ', 'working'),
('The Power of Love', 'Celine Dion', 1994, 'Y8HOfcYWZoo', 'working'),
('Basket Case', 'Green Day', 1994, 'NUTGr5t3MoY', 'working'),
('Cotton Eye Joe', 'Rednex', 1994, 'mOYZaiDZ7BM', 'working'),
('Black Hole Sun', 'Soundgarden', 1994, '3mbBbFH9fAg', 'working'),
('Creep', 'TLC', 1994, 'LlZydtG3xqI', 'working'),
('Zombie', 'The Cranberries', 1994, '6Ejga4kJUts', 'working'),
('You Oughta Know', 'Alanis Morissette', 1995, 'NPcyTyilmYY', 'working'),
('Gangsta''s Paradise', 'Coolio', 1995, 'fPO76Jlnz6c', 'working'),
('Breakfast at Tiffany''s', 'Deep Blue Something', 1995, '1ClCpfeIELw', 'working'),
('One of Us', 'Joan Osborne', 1995, 'B4CRkpBGQzU', 'working'),
('Wonderwall', 'Oasis', 1995, 'bx1Bh8ZvH84', 'working'),
('Kiss from a Rose', 'Seal', 1995, 'AMD2TwRvuoU', 'working'),
('Waterfalls', 'TLC', 1995, '8WEtxJ4-sh4', 'working'),
('I''ll Be There for You', 'The Rembrandts', 1995, 'q-9kPks0IfE', 'working'),
('How Do U Want It', '2Pac', 1996, 'VUBQLnEGHNk', 'working'),
('No Diggity', 'Blackstreet ft. Dr. Dre', 1996, '3KL9mRus19o', 'working'),
('Killing Me Softly', 'Fugees', 1996, '8ppz-cwLeqo', 'working'),
('Macarena', 'Los Del Rio', 1996, 'zWaymcVmJ-A', 'working'),
('Return of the Mack', 'Mark Morrison', 1996, 'uB1D9wWxd2w', 'working'),
('Don''t Speak', 'No Doubt', 1996, 'TR3Vdo5etCQ', 'working'),
('Wannabe', 'Spice Girls', 1996, 'gJLIiF15wjQ', 'working'),
('1979', 'The Smashing Pumpkins', 1996, '4aeETEoNfOg', 'working'),
('Barbie Girl', 'Aqua', 1997, 'ZyhrYis509A', 'working'),
('My Heart Will Go On', 'Celine Dion', 1997, 'WNIPqafd4As', 'working'),
('Tubthumping', 'Chumbawamba', 1997, '2H5uWRjFsGc', 'working'),
('MMMBop', 'Hanson', 1997, 'NHozn0YXAeE', 'working'),
('Torn', 'Natalie Imbruglia', 1997, 'VV1XWJN3nJo', 'working'),
('Bitter Sweet Symphony', 'The Verve', 1997, '1lyu1KKwC74', 'working'),
('The Freshmen', 'The Verve Pipe', 1997, '1umEXpGHc0E', 'working'),
('Semi-Charmed Life', 'Third Eye Blind', 1997, 'beINamVRGy4', 'working'),
('C''est la Vie', 'B*Witched', 1998, 'UvjLgjtJKsc', 'working'),
('...Baby One More Time', 'Britney Spears', 1998, 'C-u5WLJ9Yk4', 'working'),
('Believe', 'Cher', 1998, 'nZXRV4MezEw', 'working'),
('Iris', 'Goo Goo Dolls', 1998, 'NdYWuo9OFAw', 'working'),
('Doo Wop (That Thing)', 'Lauryn Hill', 1998, 'T6QKqFPRZSA', 'working'),
('Ray of Light', 'Madonna', 1998, 'x3ov9USxVxY', 'working'),
('Truly Madly Deeply', 'Savage Garden', 1998, 'WQnAxOQxQIU', 'working'),
('Gettin'' Jiggy wit It', 'Will Smith', 1998, '3JcmQONgXJM', 'working'),
('I Want It That Way', 'Backstreet Boys', 1999, '4fndeDfaWCg', 'working'),
('Genie in a Bottle', 'Christina Aguilera', 1999, 'kIDWgqDBNXA', 'working'),
('Bills, Bills, Bills', 'Destiny''s Child', 1999, 'NiF6-0UTqtc', 'working'),
('Livin'' la Vida Loca', 'Ricky Martin', 1999, 'p47fEXGabaY', 'working'),
('Smooth', 'Santana ft. Rob Thomas', 1999, '6Whgn_iE5uc', 'working'),
('Kiss Me', 'Sixpence None the Richer', 1999, '8N-qO3sPMjc', 'working'),
('All Star', 'Smash Mouth', 1999, 'L_jWHffIx5E', 'working'),
('No Scrubs', 'TLC', 1999, 'FrLequ6dUdM', 'working'),
('Bye Bye Bye', '*NSYNC', 2000, 'Eo-KmOd3i7s', 'working'),
('Who Let the Dogs Out', 'Baha Men', 2000, 'Qkuu0Lwb5EM', 'working'),
('Oops!... I Did It Again', 'Britney Spears', 2000, 'CduA0TULnow', 'working'),
('Independent Women', 'Destiny''s Child', 2000, '0lPQZni7I18', 'working'),
('Say My Name', 'Destiny''s Child', 2000, 'sQgd6MccwZc', 'working'),
('The Real Slim Shady', 'Eminem', 2000, 'eJO5HU_7_1w', 'working'),
('Music', 'Madonna', 2000, 'Sdz2oW0NMFk', 'working'),
('It Wasn''t Me', 'Shaggy', 2000, 'T_x6QmuJdms', 'working'),
('Beautiful Day', 'U2', 2000, 'co6WMzDOh1o', 'working'),
('Fallin''', 'Alicia Keys', 2001, 'Urdlvw0SSEc', 'working'),
('Lady Marmalade', 'Christina Aguilera, Lil'' Kim, Mýa, Pink', 2001, 'RQa7SvVCdZk', 'working'),
('In the End', 'Linkin Park', 2001, 'eVTXPUF4Oz4', 'working'),
('Get Ur Freak On', 'Missy Elliott', 2001, 'FPoKiGQzbSQ', 'working'),
('Sk8er Boi', 'Avril Lavigne', 2002, 'TIy3n2b7V9k', 'working'),
('Complicated', 'Avril Lavigne', 2002, '5NPBIwQyPWE', 'working'),
('Without Me', 'Eminem', 2002, 'YVkUvmDQ3HY', 'working'),
('Lose Yourself', 'Eminem', 2002, '_Yhyp-_hX2s', 'working'),
('Hot in Herre', 'Nelly', 2002, 'GeZZr_p6vB8', 'working'),
('A Thousand Miles', 'Vanessa Carlton', 2002, 'Cwkej79U3ek', 'working'),
('In Da Club', '50 Cent', 2003, '5qm8PH4xAss', 'working'),
('Crazy in Love', 'Beyoncé ft. Jay-Z', 2003, 'ViwtNLUqkMY', 'working'),
('Where Is the Love?', 'Black Eyed Peas', 2003, 'WpYeekQkAdc', 'working'),
('Beautiful', 'Christina Aguilera', 2003, 'eAfyFTzZDMM', 'working'),
('Hey Ya!', 'OutKast', 2003, 'PWgvGjAhvIw', 'working'),
('Toxic', 'Britney Spears', 2004, 'LOZuxwVk7TU', 'working'),
('Boulevard of Broken Dreams', 'Green Day', 2004, 'Soa3gO7tL-c', 'working'),
('Since U Been Gone', 'Kelly Clarkson', 2004, 'R7UrFYvl5TE', 'working'),
('Drop It Like It''s Hot', 'Snoop Dogg ft. Pharrell', 2004, 'RaCodgL9cvk', 'working'),
('Mr. Brightside', 'The Killers', 2004, 'gGdGFtwCNBE', 'working'),
('Yeah!', 'Usher ft. Lil Jon & Ludacris', 2004, 'GxBSyx85Kp8', 'working'),
('Candy Shop', '50 Cent', 2005, 'SRcnnId15BA', 'working'),
('Feel Good Inc.', 'Gorillaz', 2005, 'HyHNuVaZJ-k', 'working'),
('Hollaback Girl', 'Gwen Stefani', 2005, 'Kgjkth6BRRY', 'working'),
('Gold Digger', 'Kanye West ft. Jamie Foxx', 2005, '6vwNcNOTVzY', 'working'),
('Irreplaceable', 'Beyoncé', 2006, '2EwViQxSJJQ', 'working'),
('Crazy', 'Gnarls Barkley', 2006, 'bd2B6SjMh_w', 'working'),
('SexyBack', 'Justin Timberlake', 2006, '3gOHvDP_vCs', 'working'),
('Promiscuous', 'Nelly Furtado ft. Timbaland', 2006, '0J3vgcE5i2o', 'working'),
('Hips Don''t Lie', 'Shakira ft. Wyclef Jean', 2006, 'DUT5rEU6pqM', 'working'),
('Buttons', 'The Pussycat Dolls', 2006, 'VCLxJd1d84s', 'working'),
('No One', 'Alicia Keys', 2007, 'rywUS-ohqeE', 'working'),
('Rehab', 'Amy Winehouse', 2007, 'KUmZp8pR1uc', 'working'),
('Big Girls Don''t Cry', 'Fergie', 2007, 'agrXgrAgQ0U', 'working'),
('The Sweet Escape', 'Gwen Stefani ft. Akon', 2007, 'O0lf_fE3HwA', 'working'),
('Umbrella', 'Rihanna ft. Jay-Z', 2007, 'CvBfHwUxHIk', 'working'),
('Apologize', 'Timbaland ft. OneRepublic', 2007, 'ZSM3w1v-A_Y', 'working'),
('Single Ladies', 'Beyoncé', 2008, '4m1EFMoRFvY', 'working'),
('Forever', 'Chris Brown', 2008, '5sMKX22BHeE', 'working'),
('Viva la Vida', 'Coldplay', 2008, 'dvgZkm1xWPE', 'working'),
('Use Somebody', 'Kings of Leon', 2008, 'gnhXHvRoUd0', 'working'),
('Just Dance', 'Lady Gaga', 2008, '2Abk1jAONjw', 'working'),
('Poker Face', 'Lady Gaga', 2008, 'bESGLojNYSo', 'working'),
('Disturbia', 'Rihanna', 2008, 'E1mU6h4Xdxc', 'working'),
('Love Story', 'Taylor Swift', 2008, '8xg3vE8Ie_E', 'working'),
('I Gotta Feeling', 'Black Eyed Peas', 2009, 'uSD4vsh1zDA', 'working'),
('Down', 'Jay Sean ft. Lil Wayne', 2009, 'oUbpGmR1-QM', 'working'),
('Tik Tok', 'Ke$ha', 2009, 'iP6XpLQM2Cs', 'working'),
('Bad Romance', 'Lady Gaga', 2009, 'qrO4YZeyl0I', 'working'),
('Fireflies', 'Owl City', 2009, 'psuRGfAaju4', 'working'),
('You Belong with Me', 'Taylor Swift', 2009, 'VuNIsY6JdUw', 'working'),
('Rolling in the Deep', 'Adele', 2010, 'rYEDA3JcQqw', 'working'),
('Just the Way You Are', 'Bruno Mars', 2010, 'LjhCEhWiKXk', 'working'),
('Love the Way You Lie', 'Eminem ft. Rihanna', 2010, 'uelHwf8o7_U', 'working'),
('Firework', 'Katy Perry', 2010, 'QGJuMBdaqIw', 'working'),
('Teenage Dream', 'Katy Perry', 2010, '98WtmW-lfeE', 'working'),
('California Gurls', 'Katy Perry ft. Snoop Dogg', 2010, 'F57P9C4SAW4', 'working'),
('We R Who We R', 'Ke$ha', 2010, 'mXvmSaE0JXA', 'working'),
('Only Girl (In the World)', 'Rihanna', 2010, 'pa14VNsdSYM', 'working'),
('Dynamite', 'Taio Cruz', 2010, 'Vysgv7qVYTo', 'working'),
('Someone Like You', 'Adele', 2011, 'hLQl3WQQoQ0', 'working'),
('Somebody That I Used to Know', 'Gotye ft. Kimbra', 2011, '8UVNT4wvIGY', 'working'),
('Party Rock Anthem', 'LMFAO', 2011, 'KQ6zr6kCPj8', 'working'),
('We Are Young', 'fun. ft. Janelle Monáe', 2011, 'Sv6dMFF_yts', 'working'),
('Call Me Maybe', 'Carly Rae Jepsen', 2012, 'fWNaR-rxAic', 'working'),
('Thrift Shop', 'Macklemore & Ryan Lewis', 2012, 'QK8mJJJvaes', 'working'),
('We Are Never Getting Back Together', 'Taylor Swift', 2012, 'WA4iX5D9Z64', 'working'),
('I Knew You Were Trouble', 'Taylor Swift', 2012, 'vNoKguSdy4Y', 'working'),
('Get Lucky', 'Daft Punk ft. Pharrell Williams', 2013, '5NV6Rdv1a3I', 'working'),
('Royals', 'Lorde', 2013, 'nlcIKh6sBtc', 'working'),
('Counting Stars', 'OneRepublic', 2013, 'hT_nvWreIhg', 'working'),
('Happy', 'Pharrell Williams', 2013, 'ZbZSe6N_BXs', 'working'),
('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 2014, 'OPf0YbXqDm0', 'working'),
('Shake It Off', 'Taylor Swift', 2014, 'nfWlot6h_JM', 'working'),
('Hello', 'Adele', 2015, 'YQHsXMglC9A', 'working'),
('Hotline Bling', 'Drake', 2015, 'uxpDa-c-4Mc', 'working'),
('Cheerleader', 'OMI', 2015, 'jGflUbPQfW8', 'working'),
('Bad Blood', 'Taylor Swift', 2015, 'QcIy9NiNbmo', 'working'),
('Can''t Feel My Face', 'The Weeknd', 2015, 'KEI4qSrkPAs', 'working'),
('See You Again', 'Wiz Khalifa ft. Charlie Puth', 2015, 'RgKAFK5djSk', 'working'),
('Can''t Stop the Feeling!', 'Justin Timberlake', 2016, 'ru0K8uYEZWw', 'working'),
('Cold Water', 'Major Lazer ft. Justin Bieber', 2016, 'a59gmGkq_pw', 'working'),
('Work', 'Rihanna ft. Drake', 2016, 'HL1UzIK-flA', 'working'),
('Don''t Let Me Down', 'The Chainsmokers', 2016, 'Io0fBr1XBUA', 'working'),
('Closer', 'The Chainsmokers ft. Halsey', 2016, 'PT2_F-1esPk', 'working'),
('Ride', 'Twenty One Pilots', 2016, 'Pw-0pbY9JeU', 'working'),
('Stressed Out', 'Twenty One Pilots', 2016, 'pXRviuL6vMY', 'working'),
('That''s What I Like', 'Bruno Mars', 2017, 'PMivT7MJ41M', 'working'),
('Havana', 'Camila Cabello', 2017, 'HCjNJDNzw8Y', 'working'),
('New Rules', 'Dua Lipa', 2017, 'k2qgadSvNyU', 'working'),
('Shape of You', 'Ed Sheeran', 2017, 'JGwWNGJdvx8', 'working'),
('Believer', 'Imagine Dragons', 2017, '7wtfhZwyrcc', 'working'),
('Thunder', 'Imagine Dragons', 2017, 'fKopy74weus', 'working'),
('Humble', 'Kendrick Lamar', 2017, 'tvTRZJ-4EyI', 'working'),
('Despacito', 'Luis Fonsi ft. Daddy Yankee', 2017, 'kJQP7kiw5Fk', 'working'),
('Rockstar', 'Post Malone ft. 21 Savage', 2017, 'UceaB4D0jpo', 'working'),
('Look What You Made Me Do', 'Taylor Swift', 2017, '3tmd-ClpJxA', 'working'),
('Something Just Like This', 'The Chainsmokers & Coldplay', 2017, 'FM7MFYoylVs', 'working'),
('Stay', 'Zedd & Alessia Cara', 2017, 'h--P8HzYZ74', 'working'),
('This Is America', 'Childish Gambino', 2018, 'VYOjWnS4cMY', 'working'),
('In My Feelings', 'Drake', 2018, 'DRS_PpOrUZ4', 'working'),
('God''s Plan', 'Drake', 2018, 'xpVfcZ0ZcFM', 'working'),
('Perfect', 'Ed Sheeran', 2018, '2Vv-BfVoq4g', 'working'),
('Without Me', 'Halsey', 2018, 'ZAfAud_M_mg', 'working'),
('Shallow', 'Lady Gaga & Bradley Cooper', 2018, 'bo_efYhYU2A', 'working'),
('Girls Like You', 'Maroon 5 ft. Cardi B', 2018, 'aJOTlE1K90k', 'working'),
('High Hopes', 'Panic! At The Disco', 2018, 'IPXIgEAGe4U', 'working'),
('Better Now', 'Post Malone', 2018, 'UYwF-jdcVjY', 'working'),
('Psycho', 'Post Malone ft. Ty Dolla Sign', 2018, 'au2n7VVGv_c', 'working'),
('Delicate', 'Taylor Swift', 2018, 'tCXGJQYZ9JA', 'working'),
('7 Rings', 'Ariana Grande', 2019, 'QYh6mYIJG2Y', 'working'),
('Bad Guy', 'Billie Eilish', 2019, 'DyDfgMOUjCI', 'working'),
('Beautiful People', 'Ed Sheeran ft. Khalid', 2019, 'mj0XInqZMHY', 'working'),
('Sucker', 'Jonas Brothers', 2019, 'CnAmeh0-E-U', 'working'),
('Someone You Loved', 'Lewis Capaldi', 2019, 'zABLecsR5UE', 'working'),
('Old Town Road', 'Lil Nas X ft. Billy Ray Cyrus', 2019, 'r7qovpFAGrQ', 'working'),
('Truth Hurts', 'Lizzo', 2019, 'P00HMxdsVZI', 'working'),
('Memories', 'Maroon 5', 2019, 'SlPhMPnQ58k', 'working'),
('Sunflower', 'Post Malone & Swae Lee', 2019, 'ApXoWvfEYVU', 'working'),
('Señorita', 'Shawn Mendes & Camila Cabello', 2019, 'Pkh8UtuejGw', 'working'),
('You Need to Calm Down', 'Taylor Swift', 2019, 'Dkk9gvTmCXY', 'working'),
('Lover', 'Taylor Swift', 2019, 'e-ORhEE9VVg', 'working'),
('ME!', 'Taylor Swift ft. Brendon Urie', 2019, 'FuXNumBwDOM', 'working'),
('Say So', 'Doja Cat', 2020, 'pok8H_KF1FA', 'working'),
('Break My Heart', 'Dua Lipa', 2020, 'Nj2U6rhnucI', 'working'),
('Physical', 'Dua Lipa', 2020, '9HDEHj2yzew', 'working'),
('Don''t Start Now', 'Dua Lipa', 2020, 'oygrmJFKYZY', 'working'),
('Watermelon Sugar', 'Harry Styles', 2020, 'E07s5ZYygMg', 'working'),
('Rain On Me', 'Lady Gaga & Ariana Grande', 2020, 'AoAm4om0wTs', 'working'),
('Circles', 'Post Malone', 2020, 'wXhTHyIgQ_U', 'working'),
('The Box', 'Roddy Ricch', 2020, 'uLHqpjW3aDs', 'working'),
('Willow', 'Taylor Swift', 2020, 'RsEZmictANA', 'working'),
('Cardigan', 'Taylor Swift', 2020, 'K-a8s8OLBSE', 'working'),
('Blinding Lights', 'The Weeknd', 2020, '4NRXx6U8ABQ', 'working'),
('Dance Monkey', 'Tones and I', 2020, 'q0hyYWKXF0Q', 'working'),
('Happier Than Ever', 'Billie Eilish', 2021, '5GJWxDKyk3A', 'working'),
('Kiss Me More', 'Doja Cat ft. SZA', 2021, '0EVVKs6DQLo', 'working'),
('Levitating', 'Dua Lipa', 2021, 'TUVcZfQe-Kw', 'working'),
('Shivers', 'Ed Sheeran', 2021, 'Il0S8BoucSA', 'working'),
('Heat Waves', 'Glass Animals', 2021, 'mRD0-GxqHVo', 'working'),
('Peaches', 'Justin Bieber ft. Daniel Caesar & Giveon', 2021, 'tQ0yjYUFKAE', 'working'),
('Montero (Call Me By Your Name)', 'Lil Nas X', 2021, '6swmTBVI83k', 'working'),
('Industry Baby', 'Lil Nas X ft. Jack Harlow', 2021, 'UTHLKHL_whs', 'working'),
('Good 4 U', 'Olivia Rodrigo', 2021, 'gNi_6U5Pm_o', 'working'),
('Drivers License', 'Olivia Rodrigo', 2021, 'ZmDBbnmKpqQ', 'working'),
('All Too Well (10 Minute Version)', 'Taylor Swift', 2021, 'tollGa3S0o8', 'working'),
('Stay', 'The Kid LAROI & Justin Bieber', 2021, 'kTJczUoc26U', 'working'),
('Save Your Tears', 'The Weeknd', 2021, 'XXYlFuWEuKI', 'working'),
('I''m Good (Blue)', 'David Guetta & Bebe Rexha', 2022, '90RLzVUuXe4', 'working'),
('Cold Heart', 'Elton John & Dua Lipa', 2022, 'qod03PVTLqk', 'working'),
('As It Was', 'Harry Styles', 2022, 'H5v3kku4y6Q', 'working'),
('Running Up That Hill', 'Kate Bush', 2022, 'wp43OdtAAkM', 'working'),
('Unholy', 'Sam Smith & Kim Petras', 2022, 'Uq9gPaIzbe8', 'working'),
('Bad Habit', 'Steve Lacy', 2022, 'VF-FGf_ZZiI', 'working'),
('Anti-Hero', 'Taylor Swift', 2022, 'b1kbLwvqugk', 'working'),
('Flowers', 'Miley Cyrus', 2023, 'G7KNmW9a75Y', 'working'),
('Det Modsatte', 'Mumle', 2023, 'mjUGJPkumhQ', 'working'),
('Vampire', 'Olivia Rodrigo', 2023, 'RlPNh_PBZb4', 'working'),
('Snooze', 'SZA', 2023, '6ZUIwj3FgUY', 'working'),
('Cruel Summer', 'Taylor Swift', 2023, 'ic8j13piAhQ', 'working'),
('Beautiful Things', 'Benson Boone', 2024, 'Oa_RSwwpPaA', 'working'),
('Hvor Solen Ik'' Skinner', 'Mumle', 2024, 'af-tBLYiqko', 'working'),
('Espresso', 'Sabrina Carpenter', 2024, 'eVli-tstM5E', 'working'),
('Please Please Please', 'Sabrina Carpenter', 2024, 'cF1Na4AIecM', 'working'),
('Die With A Smile', 'Lady Gaga & Bruno Mars', 2025, 'kPa7bsKwL-c', 'working'),
('Fire Uger', 'Mumle', 2025, 'p6Q1xQ_Z_Jw', 'working'),
('APT.', 'ROSÉ & Bruno Mars', 2025, 'ekr2nIex040', 'working');

ON CONFLICT (video_id) DO NOTHING;

-- Assign songs to playlists based on year
-- Modern: 2016-2025
INSERT INTO song_playlists (song_id, playlist_id)
SELECT s.id, c.id
FROM songs s
CROSS JOIN playlists c
WHERE c.name = 'Modern' AND s.year >= 2016
ON CONFLICT DO NOTHING;

-- Classic: 1952-2015
INSERT INTO song_playlists (song_id, playlist_id)
SELECT s.id, c.id
FROM songs s
CROSS JOIN playlists c
WHERE c.name = 'Classic' AND s.year < 2016
ON CONFLICT DO NOTHING;
