-- Song data for Hytte Hits game
-- This file contains all songs for both modern and classic playlists

-- Modern songs (2016-2025)
INSERT INTO songs (title, artist, year, video_id, playlist, status) VALUES
-- 2016
('Closer', 'The Chainsmokers ft. Halsey', 2016, 'PT2_F-1esPk', 'modern', 'working'),
('One Dance', 'Drake ft. WizKid & Kyla', 2016, 'eRTWCG0IlF0', 'modern', 'working'),
('Cheap Thrills', 'Sia', 2016, 'nYh-n7EOtma', 'modern', 'working'),
('Don''t Let Me Down', 'The Chainsmokers', 2016, 'Io0fBr1XBUA', 'modern', 'working'),
('Cold Water', 'Major Lazer ft. Justin Bieber', 2016, 'a59gmGkq_pw', 'modern', 'working'),
('Work', 'Rihanna ft. Drake', 2016, 'HL1UzIK-flA', 'modern', 'working'),
('Stressed Out', 'Twenty One Pilots', 2016, 'pXRviuL6vMY', 'modern', 'working'),
('This Is What You Came For', 'Calvin Harris ft. Rihanna', 2016, 'kOkQ4T-7XTs', 'modern', 'working'),
('Can''t Stop the Feeling!', 'Justin Timberlake', 2016, 'ru0K8uYEZWw', 'modern', 'working'),
('Ride', 'Twenty One Pilots', 2016, 'Pw-0pbY9JeU', 'modern', 'working'),
('Vesterbro', 'Lukas Graham', 2016, 'iGjQPZa4KyE', 'modern', 'working'),
('Natteravn', 'Suspekt', 2016, 'r_4fJmRJGtg', 'modern', 'working'),

-- 2017
('Shape of You', 'Ed Sheeran', 2017, 'JGwWNGJdvx8', 'modern', 'working'),
('Despacito', 'Luis Fonsi ft. Daddy Yankee', 2017, 'kJQP7kiw5Fk', 'modern', 'working'),
('Something Just Like This', 'The Chainsmokers & Coldplay', 2017, 'FM7MFYoylVs', 'modern', 'working'),
('Humble', 'Kendrick Lamar', 2017, 'tvTRZJ-4EyI', 'modern', 'working'),
('That''s What I Like', 'Bruno Mars', 2017, 'PMivT7MJ41M', 'modern', 'working'),
('Believer', 'Imagine Dragons', 2017, '7wtfhZwyrcc', 'modern', 'working'),
('Rockstar', 'Post Malone ft. 21 Savage', 2017, 'UceaB4D0jpo', 'modern', 'working'),
('Stay', 'Zedd & Alessia Cara', 2017, 'h--P8HzYZ74', 'modern', 'working'),
('Look What You Made Me Do', 'Taylor Swift', 2017, '3tmd-ClpJxA', 'modern', 'working'),
('Havana', 'Camila Cabello', 2017, 'HCjNJDNzw8Y', 'modern', 'working'),
('Thunder', 'Imagine Dragons', 2017, 'fKopy74weus', 'modern', 'working'),
('New Rules', 'Dua Lipa', 2017, 'k2qgadSvNyU', 'modern', 'working'),
('Langt Ude', 'Kesi', 2017, 'cXMT57f8e1w', 'modern', 'working'),
('Higher', 'MØ', 2017, 'p_IIpOnuJVc', 'modern', 'working'),

-- 2018
('God''s Plan', 'Drake', 2018, 'xpVfcZ0ZcFM', 'modern', 'working'),
('Perfect', 'Ed Sheeran', 2018, '2Vv-BfVoq4g', 'modern', 'working'),
('In My Feelings', 'Drake', 2018, 'DRS_PpOrUZ4', 'modern', 'working'),
('Girls Like You', 'Maroon 5 ft. Cardi B', 2018, 'aJOTlE1K90k', 'modern', 'working'),
('Psycho', 'Post Malone ft. Ty Dolla Sign', 2018, 'au2n7VVGv_c', 'modern', 'working'),
('Better Now', 'Post Malone', 2018, 'UYwF-jdcVjY', 'modern', 'working'),
('This Is America', 'Childish Gambino', 2018, 'VYOjWnS4cMY', 'modern', 'working'),
('Delicate', 'Taylor Swift', 2018, 'tCXGJQYZ9JA', 'modern', 'working'),
('Without Me', 'Halsey', 2018, 'ZAfAud_M_mg', 'modern', 'working'),
('High Hopes', 'Panic! At The Disco', 2018, 'IPXIgEAGe4U', 'modern', 'working'),
('Shallow', 'Lady Gaga & Bradley Cooper', 2018, 'bo_efYhYU2A', 'modern', 'working'),
('Tir', 'Gilli', 2018, '2iD23M1xVqU', 'modern', 'working'),
('Champagne', 'Scarlett Pleasure', 2018, '1AqcRJ1MbNk', 'modern', 'working'),

-- 2019
('Old Town Road', 'Lil Nas X ft. Billy Ray Cyrus', 2019, 'r7qovpFAGrQ', 'modern', 'working'),
('Sunflower', 'Post Malone & Swae Lee', 2019, 'ApXoWvfEYVU', 'modern', 'working'),
('Bad Guy', 'Billie Eilish', 2019, 'DyDfgMOUjCI', 'modern', 'working'),
('Señorita', 'Shawn Mendes & Camila Cabello', 2019, 'Pkh8UtuejGw', 'modern', 'working'),
('Truth Hurts', 'Lizzo', 2019, 'P00HMxdsVZI', 'modern', 'working'),
('Someone You Loved', 'Lewis Capaldi', 2019, 'zABLecsR5UE', 'modern', 'working'),
('Sucker', 'Jonas Brothers', 2019, 'CnAmeh0-E-U', 'modern', 'working'),
('7 Rings', 'Ariana Grande', 2019, 'QYh6mYIJG2Y', 'modern', 'working'),
('ME!', 'Taylor Swift ft. Brendon Urie', 2019, 'FuXNumBwDOM', 'modern', 'working'),
('You Need to Calm Down', 'Taylor Swift', 2019, 'Dkk9gvTmCXY', 'modern', 'working'),
('Lover', 'Taylor Swift', 2019, 'e-ORhEE9VVg', 'modern', 'working'),
('Before You Go', 'Lewis Capaldi', 2019, 'Jhhnmx4rM0o', 'modern', 'working'),
('Bruises', 'Lewis Capaldi', 2019, 'Oe_FsKJVOv4', 'modern', 'working'),
('Memories', 'Maroon 5', 2019, 'SlPhMPnQ58k', 'modern', 'working'),
('Beautiful People', 'Ed Sheeran ft. Khalid', 2019, 'mj0XInqZMHY', 'modern', 'working'),
('Læg Ikke Mærke Til Mig', 'Soleima', 2019, 'a7PmC1p1_7w', 'modern', 'working'),

-- 2020
('Blinding Lights', 'The Weeknd', 2020, '4NRXx6U8ABQ', 'modern', 'working'),
('Watermelon Sugar', 'Harry Styles', 2020, 'E07s5ZYygMg', 'modern', 'working'),
('Savage Love', 'Jawsh 685 & Jason Derulo', 2020, 'QLBu2PUkaYM', 'modern', 'working'),
('Rockstar', 'DaBaby ft. Roddy Ricch', 2020, 'mxFstYW6-sg', 'modern', 'working'),
('Dance Monkey', 'Tones and I', 2020, 'q0hyYWKXF0Q', 'modern', 'working'),
('Say So', 'Doja Cat', 2020, 'pok8H_KF1FA', 'modern', 'working'),
('Don''t Start Now', 'Dua Lipa', 2020, 'oygrmJFKYZY', 'modern', 'working'),
('Circles', 'Post Malone', 2020, 'wXhTHyIgQ_U', 'modern', 'working'),
('Cardigan', 'Taylor Swift', 2020, 'K-a8s8OLBSE', 'modern', 'working'),
('Willow', 'Taylor Swift', 2020, 'RsEZmictANA', 'modern', 'working'),
('Break My Heart', 'Dua Lipa', 2020, 'Nj2U6rhnucI', 'modern', 'working'),
('The Box', 'Roddy Ricch', 2020, 'uLHqpjW3aDs', 'modern', 'working'),
('Rain On Me', 'Lady Gaga & Ariana Grande', 2020, 'AoAm4om0wTs', 'modern', 'working'),
('Physical', 'Dua Lipa', 2020, '9HDEHj2yzew', 'modern', 'working'),
('Guld og Grønne Skove', 'Erika de Casier', 2020, '7fKFR8WqjsQ', 'modern', 'working'),

-- 2021
('Levitating', 'Dua Lipa', 2021, 'TUVcZfQe-Kw', 'modern', 'working'),
('Good 4 U', 'Olivia Rodrigo', 2021, 'gNi_6U5Pm_o', 'modern', 'working'),
('Montero (Call Me By Your Name)', 'Lil Nas X', 2021, '6swmTBVI83k', 'modern', 'working'),
('Stay', 'The Kid LAROI & Justin Bieber', 2021, 'kTJczUoc26U', 'modern', 'working'),
('Peaches', 'Justin Bieber ft. Daniel Caesar & Giveon', 2021, 'tQ0yjYUFKAE', 'modern', 'working'),
('Save Your Tears', 'The Weeknd', 2021, 'XXYlFuWEuKI', 'modern', 'working'),
('Kiss Me More', 'Doja Cat ft. SZA', 2021, '0EVVKs6DQLo', 'modern', 'working'),
('Drivers License', 'Olivia Rodrigo', 2021, 'ZmDBbnmKpqQ', 'modern', 'working'),
('All Too Well (10 Minute Version)', 'Taylor Swift', 2021, 'tollGa3S0o8', 'modern', 'working'),
('Traitor', 'Olivia Rodrigo', 2021, 'KphB3WaqFWY', 'modern', 'working'),
('Deja Vu', 'Olivia Rodrigo', 2021, 'qMH0Xze0XJA', 'modern', 'working'),
('Happier Than Ever', 'Billie Eilish', 2021, '5GJWxDKyk3A', 'modern', 'working'),
('Industry Baby', 'Lil Nas X ft. Jack Harlow', 2021, 'UTHLKHL_whs', 'modern', 'working'),
('Shivers', 'Ed Sheeran', 2021, 'Il0S8BoucSA', 'modern', 'working'),
('Heat Waves', 'Glass Animals', 2021, 'mRD0-GxqHVo', 'modern', 'working'),
('Alt Det Jeg Ville Have Sagt', 'Sanne Salomonsen', 2021, 'YsCxHF3gX-s', 'modern', 'working'),

-- 2022
('As It Was', 'Harry Styles', 2022, 'H5v3kku4y6Q', 'modern', 'working'),
('Anti-Hero', 'Taylor Swift', 2022, 'b1kbLwvqugk', 'modern', 'working'),
('Unholy', 'Sam Smith & Kim Petras', 2022, 'Uq9gPaIzbe8', 'modern', 'working'),
('I''m Good (Blue)', 'David Guetta & Bebe Rexha', 2022, '90RLzVUuXe4', 'modern', 'working'),
('Running Up That Hill', 'Kate Bush', 2022, 'wp43OdtAAkM', 'modern', 'working'),
('About Damn Time', 'Lizzo', 2022, 'SLjnq2BiGbE', 'modern', 'working'),
('Lavender Haze', 'Taylor Swift', 2022, 'jBwWy-YciUQ', 'modern', 'working'),
('Bad Habit', 'Steve Lacy', 2022, 'VF-FGf_ZZiI', 'modern', 'working'),
('Super Freaky Girl', 'Nicki Minaj', 2022, '3aPqFCJ2jW4', 'modern', 'working'),
('Cold Heart', 'Elton John & Dua Lipa', 2022, 'qod03PVTLqk', 'modern', 'working'),
('Until I Found You', 'Stephen Sanchez', 2022, 'jVQMEIjKfD4', 'modern', 'working'),
('Tabita', 'Natasja', 2022, 'K6lXaJqMzFw', 'modern', 'working'),

-- 2023
('Flowers', 'Miley Cyrus', 2023, 'G7KNmW9a75Y', 'modern', 'working'),
('Kill Bill', 'SZA', 2023, 'aLZ8xWEGh3g', 'modern', 'working'),
('Vampire', 'Olivia Rodrigo', 2023, 'RlPNh_PBZb4', 'modern', 'working'),
('Paint The Town Red', 'Doja Cat', 2023, 'UxESd61h8uI', 'modern', 'working'),
('Cruel Summer', 'Taylor Swift', 2023, 'ic8j13piAhQ', 'modern', 'working'),
('What Was I Made For?', 'Billie Eilish', 2023, 'j5FweitwAQ8', 'modern', 'working'),
('Dance The Night', 'Dua Lipa', 2023, 'RuRLz0pXcKU', 'modern', 'working'),
('Karma', 'Taylor Swift', 2023, 'JmnjJ12s4Z8', 'modern', 'working'),
('Get Lucky', 'Olivia Rodrigo', 2023, 'uV_mEK5MXck', 'modern', 'working'),
('Greedy', 'Tate McRae', 2023, 'I_KftYFoyGs', 'modern', 'working'),
('Snooze', 'SZA', 2023, '6ZUIwj3FgUY', 'modern', 'working'),
('Strangers', 'Kenya Grace', 2023, 'eU3vQEYct_0', 'modern', 'working'),
('Water', 'Tyla', 2023, '7aKVdLZtUMQ', 'modern', 'working'),
('Størst Af Alt', 'Burhan G ft. Medina', 2023, 'o3pWzxlI_p8', 'modern', 'working'),
('Det Modsatte', 'Mumle', 2023, 'mjUGJPkumhQ', 'modern', 'working'),

-- 2024
('Espresso', 'Sabrina Carpenter', 2024, 'eVli-tstM5E', 'modern', 'working'),
('Please Please Please', 'Sabrina Carpenter', 2024, 'cF1Na4AIecM', 'modern', 'working'),
('Beautiful Things', 'Benson Boone', 2024, 'Oa_RSwwpPaA', 'modern', 'working'),
('Fortnight', 'Taylor Swift ft. Post Malone', 2024, 'q3zkkD89qFk', 'modern', 'working'),
('Not Like Us', 'Kendrick Lamar', 2024, 'mJCW3blrHsw', 'modern', 'working'),
('Birds of a Feather', 'Billie Eilish', 2024, 'a6FdJz4oBPg', 'modern', 'working'),
('Good Luck, Babe!', 'Chappell Roan', 2024, 'xYk3RHWxVkE', 'modern', 'working'),
('Too Sweet', 'Hozier', 2024, 'EUb0LyKTaQE', 'modern', 'working'),
('I Can Do It With a Broken Heart', 'Taylor Swift', 2024, '4M46TThCu5c', 'modern', 'working'),
('Stargazing', 'Myles Smith', 2024, 'YVvQHzbJ5So', 'modern', 'working'),
('Taste', 'Sabrina Carpenter', 2024, 'I-haJoDkWTA', 'modern', 'working'),
('Obsessed', 'Olivia Rodrigo', 2024, 'XrMxSFAxSYM', 'modern', 'working'),
('Nosedive', 'Post Malone ft. Lainey Wilson', 2024, 'Ry08sXMj1C8', 'modern', 'working'),
('Sailor Song', 'Gigi Perez', 2024, 'vPDlFECPqzE', 'modern', 'working'),
('Du Er Min', 'Hej Matematik ft. Soleima', 2024, 'm0qXr6RI3KY', 'modern', 'working'),
('Hvor Solen Ik'' Skinner', 'Mumle', 2024, 'af-tBLYiqko', 'modern', 'working'),

-- 2025
('Die With A Smile', 'Lady Gaga & Bruno Mars', 2025, 'kPa7bsKwL-c', 'modern', 'working'),
('APT.', 'ROSÉ & Bruno Mars', 2025, 'ekr2nIex040', 'modern', 'working'),
('Lose Control', 'Teddy Swims', 2025, 'cS3pHKuroIw', 'modern', 'working'),
('Noid', 'Tyler, The Creator', 2025, 'oid1Ybi8vy8', 'modern', 'working'),
('Guilty as Sin?', 'Taylor Swift', 2025, '0zAcB-pxLNU', 'modern', 'working'),
('Aften', 'Soleima', 2025, '8gFLZx0X6xE', 'modern', 'working'),
('Fire Uger', 'Mumle', 2025, 'p6Q1xQ_Z_Jw', 'modern', 'working')

ON CONFLICT (video_id) DO NOTHING;

-- Classic songs (1952-2025, focus on 1970-2005)
INSERT INTO songs (title, artist, year, video_id, playlist, status) VALUES
-- 1950s
('Singin'' in the Rain', 'Gene Kelly', 1952, 'D1ZYhVpdXbQ', 'classic', 'working'),
('Rock Around the Clock', 'Bill Haley & His Comets', 1954, 'ZgdufzXvjqw', 'classic', 'working'),
('Jailhouse Rock', 'Elvis Presley', 1957, 'gj0Rz-uP4Mk', 'classic', 'working'),
('Hound Dog', 'Elvis Presley', 1956, 'MMmfjSZ_h1s', 'classic', 'working'),
('All Shook Up', 'Elvis Presley', 1957, '217dCdpZ9lM', 'classic', 'working'),
('Great Balls of Fire', 'Jerry Lee Lewis', 1957, '7IjgZGhHrYY', 'classic', 'working'),
('Johnny B. Goode', 'Chuck Berry', 1958, 'ZFo8-JqzSCM', 'classic', 'working'),
('La Bamba', 'Ritchie Valens', 1958, 'Jp6j5HJ-Cok', 'classic', 'working'),

-- 1960s
('The Twist', 'Chubby Checker', 1960, 'im9XuJJXylw', 'classic', 'working'),
('Stand by Me', 'Ben E. King', 1961, 'hwZNL7QVJjE', 'classic', 'working'),
('Can''t Help Falling in Love', 'Elvis Presley', 1961, 'vGJTaP6anOU', 'classic', 'working'),
('I Want to Hold Your Hand', 'The Beatles', 1963, 'jenWdylTtzs', 'classic', 'working'),
('She Loves You', 'The Beatles', 1963, 'pRdRg_vwcF8', 'classic', 'working'),
('Fly Me to the Moon', 'Frank Sinatra', 1964, 'ZEcqHA7dbwM', 'classic', 'working'),
('My Girl', 'The Temptations', 1964, '6IUG-9jZxHQ', 'classic', 'working'),
('I Got You (I Feel Good)', 'James Brown', 1965, 'U5TqIdff_DQ', 'classic', 'working'),
('Good Vibrations', 'The Beach Boys', 1966, 'Eab_beh07HU', 'classic', 'working'),
('What a Wonderful World', 'Louis Armstrong', 1967, 'VqhCQZaH4Vs', 'classic', 'working'),
('Respect', 'Aretha Franklin', 1967, '6FOUqQt3Kg0', 'classic', 'working'),
('Light My Fire', 'The Doors', 1967, 'deB_u-to-IE', 'classic', 'working'),
('Hey Jude', 'The Beatles', 1968, 'A_MjCqQoLLA', 'classic', 'working'),
('I Heard It Through the Grapevine', 'Marvin Gaye', 1968, 'hajBdDM2qdg', 'classic', 'working'),
('Here Comes the Sun', 'The Beatles', 1969, 'KQetemT1sWc', 'classic', 'working'),
('Come Together', 'The Beatles', 1969, '_HONxwhwmgU', 'classic', 'working'),
('Let It Be', 'The Beatles', 1970, 'QDYfEBY9NM4', 'classic', 'working'),

-- 1970s
('Imagine', 'John Lennon', 1971, 'YkgkThdzX-8', 'classic', 'working'),
('Stairway to Heaven', 'Led Zeppelin', 1971, 'QkF3oxziUI4', 'classic', 'working'),
('American Pie', 'Don McLean', 1971, 'uAsV5-Hv-7U', 'classic', 'working'),
('Superstition', 'Stevie Wonder', 1972, '0CFuCYNx-1g', 'classic', 'working'),
('Bohemian Rhapsody', 'Queen', 1975, 'fJ9rUzIMcZQ', 'classic', 'working'),
('Wish You Were Here', 'Pink Floyd', 1975, 'IXdNnw99-Ic', 'classic', 'working'),
('December, 1963', 'Frankie Valli & The Four Seasons', 1975, 'liyiT_DGREA', 'classic', 'working'),
('Hotel California', 'Eagles', 1976, 'EqPtz5qN7HM', 'classic', 'working'),
('Dancing Queen', 'ABBA', 1976, 'xFrGuyw1V8s', 'classic', 'working'),
('More Than a Feeling', 'Boston', 1976, 'SSR6ZzjDZ94', 'classic', 'working'),
('We Will Rock You', 'Queen', 1977, '-tJYN-eG1zk', 'classic', 'working'),
('Stayin'' Alive', 'Bee Gees', 1977, 'fNFzfwLM72c', 'classic', 'working'),
('Go Your Own Way', 'Fleetwood Mac', 1977, '6ul-cZyuYq4', 'classic', 'working'),
('Le Freak', 'Chic', 1978, 'h1qQ1SKNlgY', 'classic', 'working'),
('YMCA', 'Village People', 1978, 'CS9OO0S5w2k', 'classic', 'working'),
('September', 'Earth, Wind & Fire', 1978, 'Gs069dndIYk', 'classic', 'working'),
('You''re the One That I Want', 'John Travolta & Olivia Newton-John', 1978, '7oKPYe53h78', 'classic', 'working'),
('Don''t Stop Me Now', 'Queen', 1979, 'HgzGwKwLmgM', 'classic', 'working'),
('I Will Survive', 'Gloria Gaynor', 1979, 'gYkACVDFmeg', 'classic', 'working'),
('Heart of Glass', 'Blondie', 1979, 'WGU_4-5RaxU', 'classic', 'working'),

-- 1980s
('Another One Bites the Dust', 'Queen', 1980, 'rY0WxgSXdEE', 'classic', 'working'),
('Call Me', 'Blondie', 1980, 'StKVS0eI85I', 'classic', 'working'),
('Celebration', 'Kool & The Gang', 1980, '3GwjfUFyY6M', 'classic', 'working'),
('Don''t You Want Me', 'The Human League', 1981, 'uPudE8nDog0', 'classic', 'working'),
('Don''t Stop Believin''', 'Journey', 1981, '1k8craCGpgs', 'classic', 'working'),
('Physical', 'Olivia Newton-John', 1981, 'vWz9VN40nCA', 'classic', 'working'),
('Eye of the Tiger', 'Survivor', 1982, 'btPJPFnesV4', 'classic', 'working'),
('Billie Jean', 'Michael Jackson', 1982, 'Zi_XLOBDo_Y', 'classic', 'working'),
('Thriller', 'Michael Jackson', 1982, 'sOnqjkJTMaA', 'classic', 'working'),
('Beat It', 'Michael Jackson', 1982, 'oRdxUFDoQe0', 'classic', 'working'),
('Africa', 'Toto', 1982, 'FTQbiNvZqaY', 'classic', 'working'),
('Hungry Like the Wolf', 'Duran Duran', 1982, 'oJL-lCzEXgI', 'classic', 'working'),
('Sweet Dreams', 'Eurythmics', 1983, 'qeMFqkcPYcg', 'classic', 'working'),
('Karma Chameleon', 'Culture Club', 1983, 'JmcA9LIIXWw', 'classic', 'working'),
('Every Breath You Take', 'The Police', 1983, 'OMOGaugKpzs', 'classic', 'working'),
('Girls Just Want to Have Fun', 'Cyndi Lauper', 1983, 'PIb6AZdTr-A', 'classic', 'working'),
('Total Eclipse of the Heart', 'Bonnie Tyler', 1983, 'lcOxhH8N3Bo', 'classic', 'working'),
('Like a Virgin', 'Madonna', 1984, 's__rX_WL100', 'classic', 'working'),
('Purple Rain', 'Prince', 1984, 'TvnYmWpD_T8', 'classic', 'working'),
('When Doves Cry', 'Prince', 1984, 'UG3VcCAlUgE', 'classic', 'working'),
('Footloose', 'Kenny Loggins', 1984, 'wFWDGTVYqE8', 'classic', 'working'),
('What''s Love Got to Do with It', 'Tina Turner', 1984, 'oGpFcHTxjZs', 'classic', 'working'),
('Careless Whisper', 'Wham!', 1984, 'izGwDsrQ1eQ', 'classic', 'working'),
('Take On Me', 'a-ha', 1985, 'djV11Xbc914', 'classic', 'working'),
('Don''t You (Forget About Me)', 'Simple Minds', 1985, 'CdqoNKCCt7A', 'classic', 'working'),
('We Built This City', 'Starship', 1985, 'K1b8AhIsSYQ', 'classic', 'working'),
('Livin'' on a Prayer', 'Bon Jovi', 1986, 'lDK9QqIzhwk', 'classic', 'working'),
('The Final Countdown', 'Europe', 1986, '9jK-NcRmVcw', 'classic', 'working'),
('Walk Like an Egyptian', 'The Bangles', 1986, 'Cv6tuzHUuuk', 'classic', 'working'),
('You Give Love a Bad Name', 'Bon Jovi', 1986, 'KrZHPOeOxQQ', 'classic', 'working'),
('Sweet Child O'' Mine', 'Guns N'' Roses', 1987, '1w7OgIMMRc4', 'classic', 'working'),
('Never Gonna Give You Up', 'Rick Astley', 1987, 'dQw4w9WgXcQ', 'classic', 'working'),
('I Wanna Dance with Somebody', 'Whitney Houston', 1987, 'eH3giaIzONA', 'classic', 'working'),
('With or Without You', 'U2', 1987, 'XmSdTa9kaiQ', 'classic', 'working'),
('Faith', 'George Michael', 1987, 'lu3VTngm1F0', 'classic', 'working'),
('Man in the Mirror', 'Michael Jackson', 1988, 'PivWY9wn5ps', 'classic', 'working'),
('Don''t Worry, Be Happy', 'Bobby McFerrin', 1988, 'd-diB65scQU', 'classic', 'working'),
('Paradise City', 'Guns N'' Roses', 1988, 'Rbm6GXllBiw', 'classic', 'working'),
('Desire', 'U2', 1988, 'CFr6RCiJ8rA', 'classic', 'working'),
('Like a Prayer', 'Madonna', 1989, '79fzeNUqQbQ', 'classic', 'working'),
('Eternal Flame', 'The Bangles', 1989, 'PSoOFn3wQV4', 'classic', 'working'),
('Straight Up', 'Paula Abdul', 1989, 'El1kgCqD7Xk', 'classic', 'working'),
('She Drives Me Crazy', 'Fine Young Cannibals', 1989, 'UtvmTu4zAMg', 'classic', 'working'),
('Pump Up the Jam', 'Technotronic', 1989, '9EcjWd-O4jI', 'classic', 'working'),
('Love Shack', 'The B-52''s', 1989, '9SOryJvTAGs', 'classic', 'working'),

-- 1990s
('Vogue', 'Madonna', 1990, 'GuJQSAiODqI', 'classic', 'working'),
('Nothing Compares 2 U', 'Sinéad O''Connor', 1990, '0-EF60neguk', 'classic', 'working'),
('Ice Ice Baby', 'Vanilla Ice', 1990, 'rog8ou-ZepE', 'classic', 'working'),
('U Can''t Touch This', 'MC Hammer', 1990, 'otCpCn0l4Wo', 'classic', 'working'),
('Wind of Change', 'Scorpions', 1990, 'n4RjJKxsamQ', 'classic', 'working'),
('Smells Like Teen Spirit', 'Nirvana', 1991, 'hTWKbfoikeg', 'classic', 'working'),
('Losing My Religion', 'R.E.M.', 1991, 'xwtdhWltSIg', 'classic', 'working'),
('Enter Sandman', 'Metallica', 1991, 'CD-E-LDc384', 'classic', 'working'),
('I Will Always Love You', 'Whitney Houston', 1992, '3JWTaaS7LdU', 'classic', 'working'),
('Creep', 'Radiohead', 1992, 'XFkzRNyygfk', 'classic', 'working'),
('Under the Bridge', 'Red Hot Chili Peppers', 1992, 'GLvohMXgcBo', 'classic', 'working'),
('Tears in Heaven', 'Eric Clapton', 1992, 'JxPj3GAYYZ0', 'classic', 'working'),
('Rhythm Is a Dancer', 'Snap!', 1992, 'u5CIqrRQl0s', 'classic', 'working'),
('Dreams', 'The Cranberries', 1993, 'Yam5uK6e-bQ', 'classic', 'working'),
('What''s Up?', '4 Non Blondes', 1993, '6NXnxTNIWkc', 'classic', 'working'),
('What Is Love', 'Haddaway', 1993, 'HEXWRTEbj1I', 'classic', 'working'),
('Mr. Vain', 'Culture Beat', 1993, 'mfWifbRdDCg', 'classic', 'working'),
('The Sign', 'Ace of Base', 1993, 'iqu132vTl5Y', 'classic', 'working'),
('Zombie', 'The Cranberries', 1994, '6Ejga4kJUts', 'classic', 'working'),
('Black Hole Sun', 'Soundgarden', 1994, '3mbBbFH9fAg', 'classic', 'working'),
('All I Wanna Do', 'Sheryl Crow', 1994, '6mEfYew1bE0', 'classic', 'working'),
('Stay (I Missed You)', 'Lisa Loeb', 1994, 'i9HGwRWMtyQ', 'classic', 'working'),
('Bump n'' Grind', 'R. Kelly', 1994, 'uAXxkNaRkp8', 'classic', 'working'),
('The Power of Love', 'Celine Dion', 1994, 'Y8HOfcYWZoo', 'classic', 'working'),
('Cotton Eye Joe', 'Rednex', 1994, 'mOYZaiDZ7BM', 'classic', 'working'),
('Basket Case', 'Green Day', 1994, 'NUTGr5t3MoY', 'classic', 'working'),
('Creep', 'TLC', 1994, 'LlZydtG3xqI', 'classic', 'working'),
('Gangsta''s Paradise', 'Coolio', 1995, 'fPO76Jlnz6c', 'classic', 'working'),
('Wonderwall', 'Oasis', 1995, 'bx1Bh8ZvH84', 'classic', 'working'),
('Waterfalls', 'TLC', 1995, '8WEtxJ4-sh4', 'classic', 'working'),
('Kiss from a Rose', 'Seal', 1995, 'AMD2TwRvuoU', 'classic', 'working'),
('One of Us', 'Joan Osborne', 1995, 'B4CRkpBGQzU', 'classic', 'working'),
('You Oughta Know', 'Alanis Morissette', 1995, 'NPcyTyilmYY', 'classic', 'working'),
('I''ll Be There for You', 'The Rembrandts', 1995, 'q-9kPks0IfE', 'classic', 'working'),
('Breakfast at Tiffany''s', 'Deep Blue Something', 1995, '1ClCpfeIELw', 'classic', 'working'),
('Wannabe', 'Spice Girls', 1996, 'gJLIiF15wjQ', 'classic', 'working'),
('Macarena', 'Los Del Rio', 1996, 'zWaymcVmJ-A', 'classic', 'working'),
('Don''t Speak', 'No Doubt', 1996, 'TR3Vdo5etCQ', 'classic', 'working'),
('No Diggity', 'Blackstreet ft. Dr. Dre', 1996, '3KL9mRus19o', 'classic', 'working'),
('How Do U Want It', '2Pac', 1996, 'VUBQLnEGHNk', 'classic', 'working'),
('1979', 'The Smashing Pumpkins', 1996, '4aeETEoNfOg', 'classic', 'working'),
('Killing Me Softly', 'Fugees', 1996, '8ppz-cwLeqo', 'classic', 'working'),
('Return of the Mack', 'Mark Morrison', 1996, 'uB1D9wWxd2w', 'classic', 'working'),
('My Heart Will Go On', 'Celine Dion', 1997, 'WNIPqafd4As', 'classic', 'working'),
('Bitter Sweet Symphony', 'The Verve', 1997, '1lyu1KKwC74', 'classic', 'working'),
('Torn', 'Natalie Imbruglia', 1997, 'VV1XWJN3nJo', 'classic', 'working'),
('MMMBop', 'Hanson', 1997, 'NHozn0YXAeE', 'classic', 'working'),
('Semi-Charmed Life', 'Third Eye Blind', 1997, 'beINamVRGy4', 'classic', 'working'),
('I''ll Be Missing You', 'Puff Daddy & Faith Evans', 1997, 'mM0-ZwUm5a0', 'classic', 'working'),
('Candle in the Wind 1997', 'Elton John', 1997, '80-TvxgUUWE', 'classic', 'working'),
('Barbie Girl', 'Aqua', 1997, 'ZyhrYis509A', 'classic', 'working'),
('The Freshmen', 'The Verve Pipe', 1997, '1umEXpGHc0E', 'classic', 'working'),
('Tubthumping', 'Chumbawamba', 1997, '2H5uWRjFsGc', 'classic', 'working'),
('...Baby One More Time', 'Britney Spears', 1998, 'C-u5WLJ9Yk4', 'classic', 'working'),
('Believe', 'Cher', 1998, 'nZXRV4MezEw', 'classic', 'working'),
('Iris', 'Goo Goo Dolls', 1998, 'NdYWuo9OFAw', 'classic', 'working'),
('Doo Wop (That Thing)', 'Lauryn Hill', 1998, 'T6QKqFPRZSA', 'classic', 'working'),
('Truly Madly Deeply', 'Savage Garden', 1998, 'WQnAxOQxQIU', 'classic', 'working'),
('Ray of Light', 'Madonna', 1998, 'x3ov9USxVxY', 'classic', 'working'),
('Gettin'' Jiggy wit It', 'Will Smith', 1998, '3JcmQONgXJM', 'classic', 'working'),
('C''est la Vie', 'B*Witched', 1998, 'UvjLgjtJKsc', 'classic', 'working'),
('Livin'' la Vida Loca', 'Ricky Martin', 1999, 'p47fEXGabaY', 'classic', 'working'),
('No Scrubs', 'TLC', 1999, 'FrLequ6dUdM', 'classic', 'working'),
('I Want It That Way', 'Backstreet Boys', 1999, '4fndeDfaWCg', 'classic', 'working'),
('Smooth', 'Santana ft. Rob Thomas', 1999, '6Whgn_iE5uc', 'classic', 'working'),
('Genie in a Bottle', 'Christina Aguilera', 1999, 'kIDWgqDBNXA', 'classic', 'working'),
('Bills, Bills, Bills', 'Destiny''s Child', 1999, 'NiF6-0UTqtc', 'classic', 'working'),
('Bailamos', 'Enrique Iglesias', 1999, 'vPhdIQ3hOBU', 'classic', 'working'),
('Kiss Me', 'Sixpence None the Richer', 1999, '8N-qO3sPMjc', 'classic', 'working'),
('All Star', 'Smash Mouth', 1999, 'L_jWHffIx5E', 'classic', 'working'),

-- 2000s
('Oops!... I Did It Again', 'Britney Spears', 2000, 'CduA0TULnow', 'classic', 'working'),
('It Wasn''t Me', 'Shaggy', 2000, 'T_x6QmuJdms', 'classic', 'working'),
('Beautiful Day', 'U2', 2000, 'co6WMzDOh1o', 'classic', 'working'),
('Bye Bye Bye', '*NSYNC', 2000, 'Eo-KmOd3i7s', 'classic', 'working'),
('Say My Name', 'Destiny''s Child', 2000, 'sQgd6MccwZc', 'classic', 'working'),
('Independent Women', 'Destiny''s Child', 2000, '0lPQZni7I18', 'classic', 'working'),
('Music', 'Madonna', 2000, 'Sdz2oW0NMFk', 'classic', 'working'),
('The Real Slim Shady', 'Eminem', 2000, 'eJO5HU_7_1w', 'classic', 'working'),
('Who Let the Dogs Out', 'Baha Men', 2000, 'Qkuu0Lwb5EM', 'classic', 'working'),
('Lady Marmalade', 'Christina Aguilera, Lil'' Kim, Mýa, Pink', 2001, 'RQa7SvVCdZk', 'classic', 'working'),
('In the End', 'Linkin Park', 2001, 'eVTXPUF4Oz4', 'classic', 'working'),
('Fallin''', 'Alicia Keys', 2001, 'Urdlvw0SSEc', 'classic', 'working'),
('Get Ur Freak On', 'Missy Elliott', 2001, 'FPoKiGQzbSQ', 'classic', 'working'),
('U Remind Me', 'Usher', 2001, 'YfNH1EqJiCk', 'classic', 'working'),
('Complicated', 'Avril Lavigne', 2002, '5NPBIwQyPWE', 'classic', 'working'),
('Without Me', 'Eminem', 2002, 'YVkUvmDQ3HY', 'classic', 'working'),
('Hot in Herre', 'Nelly', 2002, 'GeZZr_p6vB8', 'classic', 'working'),
('A Thousand Miles', 'Vanessa Carlton', 2002, 'Cwkej79U3ek', 'classic', 'working'),
('Lose Yourself', 'Eminem', 2002, '_Yhyp-_hX2s', 'classic', 'working'),
('Sk8er Boi', 'Avril Lavigne', 2002, 'TIy3n2b7V9k', 'classic', 'working'),
('Crazy in Love', 'Beyoncé ft. Jay-Z', 2003, 'ViwtNLUqkMY', 'classic', 'working'),
('Hey Ya!', 'OutKast', 2003, 'PWgvGjAhvIw', 'classic', 'working'),
('In Da Club', '50 Cent', 2003, '5qm8PH4xAss', 'classic', 'working'),
('Beautiful', 'Christina Aguilera', 2003, 'eAfyFTzZDMM', 'classic', 'working'),
('Where Is the Love?', 'Black Eyed Peas', 2003, 'WpYeekQkAdc', 'classic', 'working'),
('Toxic', 'Britney Spears', 2004, 'LOZuxwVk7TU', 'classic', 'working'),
('Yeah!', 'Usher ft. Lil Jon & Ludacris', 2004, 'GxBSyx85Kp8', 'classic', 'working'),
('Boulevard of Broken Dreams', 'Green Day', 2004, 'Soa3gO7tL-c', 'classic', 'working'),
('Since U Been Gone', 'Kelly Clarkson', 2004, 'R7UrFYvl5TE', 'classic', 'working'),
('Mr. Brightside', 'The Killers', 2004, 'gGdGFtwCNBE', 'classic', 'working'),
('Drop It Like It''s Hot', 'Snoop Dogg ft. Pharrell', 2004, 'RaCodgL9cvk', 'classic', 'working'),
('Gold Digger', 'Kanye West ft. Jamie Foxx', 2005, '6vwNcNOTVzY', 'classic', 'working'),
('Hollaback Girl', 'Gwen Stefani', 2005, 'Kgjkth6BRRY', 'classic', 'working'),
('Candy Shop', '50 Cent', 2005, 'SRcnnId15BA', 'classic', 'working'),
('Feel Good Inc.', 'Gorillaz', 2005, 'HyHNuVaZJ-k', 'classic', 'working'),
('Hips Don''t Lie', 'Shakira ft. Wyclef Jean', 2006, 'DUT5rEU6pqM', 'classic', 'working'),
('SexyBack', 'Justin Timberlake', 2006, '3gOHvDP_vCs', 'classic', 'working'),
('Promiscuous', 'Nelly Furtado ft. Timbaland', 2006, '0J3vgcE5i2o', 'classic', 'working'),
('Irreplaceable', 'Beyoncé', 2006, '2EwViQxSJJQ', 'classic', 'working'),
('Buttons', 'The Pussycat Dolls', 2006, 'VCLxJd1d84s', 'classic', 'working'),
('SOS', 'Rihanna', 2006, 'GkHAWf0sR_4', 'classic', 'working'),
('Crazy', 'Gnarls Barkley', 2006, 'bd2B6SjMh_w', 'classic', 'working'),
('Umbrella', 'Rihanna ft. Jay-Z', 2007, 'CvBfHwUxHIk', 'classic', 'working'),
('Rehab', 'Amy Winehouse', 2007, 'KUmZp8pR1uc', 'classic', 'working'),
('Apologize', 'Timbaland ft. OneRepublic', 2007, 'ZSM3w1v-A_Y', 'classic', 'working'),
('No One', 'Alicia Keys', 2007, 'rywUS-ohqeE', 'classic', 'working'),
('Big Girls Don''t Cry', 'Fergie', 2007, 'agrXgrAgQ0U', 'classic', 'working'),
('The Sweet Escape', 'Gwen Stefani ft. Akon', 2007, 'O0lf_fE3HwA', 'classic', 'working'),
('Single Ladies', 'Beyoncé', 2008, '4m1EFMoRFvY', 'classic', 'working'),
('Poker Face', 'Lady Gaga', 2008, 'bESGLojNYSo', 'classic', 'working'),
('Viva la Vida', 'Coldplay', 2008, 'dvgZkm1xWPE', 'classic', 'working'),
('Love Story', 'Taylor Swift', 2008, '8xg3vE8Ie_E', 'classic', 'working'),
('Just Dance', 'Lady Gaga', 2008, '2Abk1jAONjw', 'classic', 'working'),
('Disturbia', 'Rihanna', 2008, 'E1mU6h4Xdxc', 'classic', 'working'),
('Forever', 'Chris Brown', 2008, '5sMKX22BHeE', 'classic', 'working'),
('Use Somebody', 'Kings of Leon', 2008, 'gnhXHvRoUd0', 'classic', 'working'),
('You Belong with Me', 'Taylor Swift', 2009, 'VuNIsY6JdUw', 'classic', 'working'),
('Tik Tok', 'Ke$ha', 2009, 'iP6XpLQM2Cs', 'classic', 'working'),
('I Gotta Feeling', 'Black Eyed Peas', 2009, 'uSD4vsh1zDA', 'classic', 'working'),
('Bad Romance', 'Lady Gaga', 2009, 'qrO4YZeyl0I', 'classic', 'working'),
('Empire State of Mind', 'Jay-Z ft. Alicia Keys', 2009, '0UjsXo9l6I8', 'classic', 'working'),
('Down', 'Jay Sean ft. Lil Wayne', 2009, 'oUbpGmR1-QM', 'classic', 'working'),
('Fireflies', 'Owl City', 2009, 'psuRGfAaju4', 'classic', 'working'),
('Rolling in the Deep', 'Adele', 2010, 'rYEDA3JcQqw', 'classic', 'working'),
('Firework', 'Katy Perry', 2010, 'QGJuMBdaqIw', 'classic', 'working'),
('California Gurls', 'Katy Perry ft. Snoop Dogg', 2010, 'F57P9C4SAW4', 'classic', 'working'),
('Love the Way You Lie', 'Eminem ft. Rihanna', 2010, 'uelHwf8o7_U', 'classic', 'working'),
('Dynamite', 'Taio Cruz', 2010, 'Vysgv7qVYTo', 'classic', 'working'),
('Only Girl (In the World)', 'Rihanna', 2010, 'pa14VNsdSYM', 'classic', 'working'),
('Teenage Dream', 'Katy Perry', 2010, '98WtmW-lfeE', 'classic', 'working'),
('Just the Way You Are', 'Bruno Mars', 2010, 'LjhCEhWiKXk', 'classic', 'working'),
('We R Who We R', 'Ke$ha', 2010, 'mXvmSaE0JXA', 'classic', 'working'),

-- 2010s
('Party Rock Anthem', 'LMFAO', 2011, 'KQ6zr6kCPj8', 'classic', 'working'),
('Someone Like You', 'Adele', 2011, 'hLQl3WQQoQ0', 'classic', 'working'),
('We Are Young', 'fun. ft. Janelle Monáe', 2011, 'Sv6dMFF_yts', 'classic', 'working'),
('Somebody That I Used to Know', 'Gotye ft. Kimbra', 2011, '8UVNT4wvIGY', 'classic', 'working'),
('Call Me Maybe', 'Carly Rae Jepsen', 2012, 'fWNaR-rxAic', 'classic', 'working'),
('Thrift Shop', 'Macklemore & Ryan Lewis', 2012, 'QK8mJJJvaes', 'classic', 'working'),
('We Are Never Getting Back Together', 'Taylor Swift', 2012, 'WA4iX5D9Z64', 'classic', 'working'),
('I Knew You Were Trouble', 'Taylor Swift', 2012, 'vNoKguSdy4Y', 'classic', 'working'),
('Get Lucky', 'Daft Punk ft. Pharrell Williams', 2013, '5NV6Rdv1a3I', 'classic', 'working'),
('Happy', 'Pharrell Williams', 2013, 'ZbZSe6N_BXs', 'classic', 'working'),
('Royals', 'Lorde', 2013, 'nlcIKh6sBtc', 'classic', 'working'),
('Counting Stars', 'OneRepublic', 2013, 'hT_nvWreIhg', 'classic', 'working'),
('Shake It Off', 'Taylor Swift', 2014, 'nfWlot6h_JM', 'classic', 'working'),
('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 2014, 'OPf0YbXqDm0', 'classic', 'working'),
('Blank Space', 'Taylor Swift', 2014, 'e-ORhEE9VVg', 'classic', 'working'),
('Bad Blood', 'Taylor Swift', 2015, 'QcIy9NiNbmo', 'classic', 'working'),
('See You Again', 'Wiz Khalifa ft. Charlie Puth', 2015, 'RgKAFK5djSk', 'classic', 'working'),
('Hello', 'Adele', 2015, 'YQHsXMglC9A', 'classic', 'working'),
('Can''t Feel My Face', 'The Weeknd', 2015, 'KEI4qSrkPAs', 'classic', 'working'),
('Cheerleader', 'OMI', 2015, 'jGflUbPQfW8', 'classic', 'working'),
('Hotline Bling', 'Drake', 2015, 'uxpDa-c-4Mc', 'classic', 'working')

ON CONFLICT (video_id) DO NOTHING;
